### ISSUE TITLE
Support Ruby 2.7

### ISSUE THREAD

**Issue by balasankarc** [rudionrails/yell#57]
Running `bundle exec rspec` on Ruby 2.7 yields the following results

```
Failures:

  1) Yell::Level given a String complex string with precise boundaries should be valid
     Failure/Error: expect(level.at?(:info)).to be_truthy

       expected: truthy value
            got: false
     # ./spec/yell/level_spec.rb:125:in `block (4 levels) in <top (required)>'

  2) Yell::Level given a String complex string with combined boundaries should be valid
     Failure/Error: expect(level.at?(:error)).to be_truthy

       expected: truthy value
            got: false
     # ./spec/yell/level_spec.rb:139:in `block (4 levels) in <top (required)>'

  3) Yell::Level given an Array should return correctly
     Failure/Error: expect(level.at?(:debug)).to be_truthy

       expected: truthy value
            got: false
     # ./spec/yell/level_spec.rb:149:in `block (3 levels) in <top (required)>'

Finished in 3.39 seconds (files took 0.47403 seconds to load)
184 examples, 3 failures

Failed examples:

rspec ./spec/yell/level_spec.rb:123 # Yell::Level given a String complex string with precise boundaries should be valid
rspec ./spec/yell/level_spec.rb:135 # Yell::Level given a String complex string with combined boundaries should be valid
rspec ./spec/yell/level_spec.rb:148 # Yell::Level given an Array should return correctly
```

**Comment by balasankarc** [comment]
The `taint` feature, used in lib/yell/level.rb has been deprecated in 2.7 - https://bugs.ruby-lang.org/issues/16131

**Comment by balasankarc** [comment]
Using an attribute for tainting seems like a quickfix

```diff
diff --git a/lib/yell/level.rb b/lib/yell/level.rb
index 8ec2ea8..9e0a547 100644
--- a/lib/yell/level.rb
+++ b/lib/yell/level.rb
@@ -42,6 +42,7 @@ module Yell #:nodoc:
     # @param [Integer,String,Symbol,Array,Range,nil] severity The severity for the level.
     def initialize( *severities )
       set(*severities)
+      @tainted = false
     end
 
     # Set the severity to the given format
@@ -176,7 +177,7 @@ module Yell #:nodoc:
       else set!( index ) # :==
       end
 
-      taint unless tainted?
+      @tainted = true unless @tainted
     end
 
     def index_from( severity )
@@ -203,7 +204,7 @@ module Yell #:nodoc:
     end
 
     def set!( index, val = true )
-      @severities.map! { false } unless tainted?
+      @severities.map! { false } unless @tainted
 
       @severities[index] = val
     end
```

But there may be more elegant solutions. :man_shrugging:

**Comment by rudionrails** [comment]
PR is merged, thanks!
